cloudfoundry-attic/cf-release

jobs/login/templates/login.yml.erb

If it exists, you know.
Signed-off-by: Filip Hanik <fhanik@gopivotal.com>

Drop saml provider with empty idpAlias [#85480674]

---

config/blobs.yml
packages/buildpack_ruby/packaging
packages/buildpack_ruby/spec

Upgrading ruby buildpack to v1.2.1

---

config/blobs.yml
packages/buildpack_go/packaging
packages/buildpack_go/spec

Upgrading to latest stable version of go buildpack

Upgrading go buildpack to v1.1.2

---

config/blobs.yml
packages/buildpack_python/packaging
packages/buildpack_python/spec

Upgrading python buildpack to v1.1.2

---

spec/fixtures/aws/cf-manifest.yml.erb
spec/fixtures/openstack/cf-manifest.yml.erb
spec/fixtures/vsphere/cf-manifest.yml.erb
spec/fixtures/warden/cf-manifest.yml.erb
templates/cf-jobs.yml

Added properties to postgres and nfs so colocated jobs can find their own ip. eg consul

Added networks properties for postgres and nfs

---

config/blobs.yml
packages/buildpack_php/packaging
packages/buildpack_php/spec

Upgrading php buildpack to v3.0.4

---

config/blobs.yml
packages/buildpack_nodejs/packaging
packages/buildpack_nodejs/spec

Upgrading nodejs buildpack to v1.2.1

---

config/blobs.yml
packages/buildpack_ruby/packaging
packages/buildpack_ruby/spec

Upgrading ruby buildpack to v1.3.1

---

config/blobs.yml
packages/buildpack_php/packaging
packages/buildpack_php/spec

Upgrading php buildpack to v3.1.1

---

config/blobs.yml
packages/buildpack_staticfile/packaging
packages/buildpack_staticfile/spec

Releasing the latest stable version of staticfile buildpack

Releasing staticfile buildpack v1.0.0

---

config/blobs.yml
packages/buildpack_nodejs/packaging
packages/buildpack_nodejs/spec

Upgrading nodejs buildpack to v1.3.1

---

config/blobs.yml
packages/buildpack_python/packaging
packages/buildpack_python/spec

Upgrading python buildpack to v1.3.1

---

config/blobs.yml
packages/buildpack_php/packaging
packages/buildpack_php/spec

Upgrading php buildpack to v3.2.1

---

config/blobs.yml
packages/buildpack_ruby/packaging
packages/buildpack_ruby/spec

Upgrading ruby buildpack to v1.4.1

---

config/blobs.yml
packages/buildpack_binary/packaging
packages/buildpack_binary/spec

Upgrading to latest stable version of binary buildpack

Upgrading binary buildpack to v1.0.0

---

config/blobs.yml
packages/buildpack_python/packaging
packages/buildpack_python/spec

Upgrading python buildpack to v1.3.2

---

config/blobs.yml
packages/buildpack_ruby/packaging
packages/buildpack_ruby/spec

Upgrading ruby buildpack to v1.4.2

---

jobs/uaa/spec
jobs/uaa/templates/uaa.yml.erb

Added CSRF protection to multiple forms
Added index and improve search time for user.email queries
Upgrade to MariaDB JDBC 1.1.8
Fix bug for when client's have dots in their name

Upgrade to UAA 2.3.1

---

jobs/collector/monit
jobs/collector/spec

Signed-off-by: Tushar Dadlani <tdadlani@pivotal.io>

Make collector memory threshold configurable

---

config/blobs.yml
packages/buildpack_nodejs/packaging
packages/buildpack_nodejs/spec

Upgrading nodejs buildpack to v1.3.3

---

config/blobs.yml
packages/buildpack_php/packaging
packages/buildpack_php/spec

Upgrading php buildpack to v3.2.2

---

config/blobs.yml
packages/buildpack_staticfile/packaging
packages/buildpack_staticfile/spec

Upgrading to latest stable version of Staticfile buildpack

Upgrading Staticfile buildpack to v1.1.0

---

config/blobs.yml
packages/buildpack_nodejs/packaging
packages/buildpack_nodejs/spec

Upgrading nodejs buildpack to v1.3.4

---

config/blobs.yml
packages/buildpack_python/packaging
packages/buildpack_python/spec

Upgrading python buildpack to v1.3.5

---

config/blobs.yml
spec/fixtures/receipts/cflinuxfs2_receipt

Includes OpenSSL update
[#96305612]
Signed-off-by: Colin Jackson <colin.s.jackson90@gmail.com>

Bump cflinuxfs2 rootfs

---

config/blobs.yml
packages/buildpack_staticfile/packaging
packages/buildpack_staticfile/spec

Upgrading to latest stable version of staticfile buildpack

Upgrading staticfile buildpack to v1.1.1

---

config/blobs.yml
packages/buildpack_binary/packaging
packages/buildpack_binary/spec

Upgrading to latest stable version of binary buildpack

Upgrading binary buildpack to v1.0.1

---

config/blobs.yml
packages/buildpack_staticfile/packaging
packages/buildpack_staticfile/spec

Upgrading to latest stable version of staticfile buildpack

Upgrading staticfile buildpack to v1.2.0

---

config/blobs.yml
packages/buildpack_python/packaging
packages/buildpack_python/spec

Upgrading python buildpack to v1.4.0

---

config/blobs.yml
packages/buildpack_php/packaging
packages/buildpack_php/spec

Upgrading php buildpack to v3.3.0

---

config/blobs.yml
packages/buildpack_ruby/packaging
packages/buildpack_ruby/spec

Upgrading ruby buildpack to v1.5.0

---

config/blobs.yml
packages/buildpack_nodejs/packaging
packages/buildpack_nodejs/spec

Upgrading nodejs buildpack to v1.4.0

---

config/blobs.yml
packages/buildpack_php/packaging
packages/buildpack_php/spec

Upgrading php buildpack to v3.3.1

---

config/blobs.yml
packages/buildpack_nodejs/packaging
packages/buildpack_nodejs/spec

Upgrading nodejs buildpack to v1.4.2

---

config/blobs.yml
packages/buildpack_ruby/packaging
packages/buildpack_ruby/spec

Upgrading ruby buildpack to v1.5.2

---

config/blobs.yml
packages/buildpack_ruby/packaging
packages/buildpack_ruby/spec

Upgrading ruby buildpack to v1.6.1

---

config/blobs.yml
packages/buildpack_staticfile/packaging
packages/buildpack_staticfile/spec

Upgrading to latest stable version of staticfile buildpack

Upgrading staticfile buildpack to v1.2.1

---

config/blobs.yml
packages/buildpack_nodejs/packaging
packages/buildpack_nodejs/spec

Upgrading nodejs buildpack to v1.5.0

---

config/blobs.yml
packages/buildpack_python/packaging
packages/buildpack_python/spec

Upgrading python buildpack to v1.5.0

---

config/blobs.yml
packages/buildpack_php/packaging
packages/buildpack_php/spec

Upgrading php buildpack to v4.0.0

---

jobs/uaa/spec
jobs/uaa/templates/log4j.properties.erb

PR for https://github.com/cloudfoundry/cf-release/issues/769
Default is still DEBUG.

Support customizing UAA logging level.

---

jobs/dea_next/spec
jobs/dea_next/templates/dea.yml.erb

Goes with https://github.com/cloudfoundry/cloud_controller_ng/pull/441

DEA needs the CC URL

---

jobs/acceptance-tests/spec
jobs/acceptance-tests/templates/config.json.erb

Signed-off-by: Jesse Alford <jalford@pivotal.io>

add properties to override buildpack names in cats [#105327596]

---

jobs/dea_next/spec
jobs/dea_next/templates/dea.yml.erb

Remove metron shared secret

---

bosh-lite/stubs/property_overrides.yml
jobs/postgres/spec
jobs/postgres/templates/postgres_start.sh.erb
jobs/postgres/templates/postgresql.conf.erb
spec/fixtures/openstack/cf-manifest.yml.erb
spec/fixtures/vsphere/cf-manifest.yml.erb
spec/fixtures/warden/cf-manifest.yml.erb
templates/cf-infrastructure-openstack.yml
templates/cf-infrastructure-vsphere.yml
templates/cf-infrastructure-warden.yml

When enabled, postgres will provide statistics about executed statements that can be used for performance analysis and optimization.
An example query could be something like:
```sql
select substring(query, 1, 100) as query,
calls,
round((total_time)::numeric, 3) as total_time,
round((total_time / calls)::numeric, 3) as mean_time
from pg_stat_statements
where dbid in (select oid from pg_database where datname = 'ccdb')
order by total_time desc limit 50;
```
and the results would be:
```
query                                                 | calls | total_time | mean_time 
------------------------------------------------------------------------------------------------------+-------+------------+-----------
SELECT * FROM "delayed_jobs" WHERE (((("run_at" <= ?) AND ("locked_at" IS NULL)) OR …
```

Configuration for `pg_stat_statements` extension

---

jobs/postgres/spec
jobs/postgres/templates/postgresql.conf.erb
spec/fixtures/openstack/cf-manifest.yml.erb
spec/fixtures/vsphere/cf-manifest.yml.erb
spec/fixtures/warden/cf-manifest.yml.erb
templates/cf-infrastructure-openstack.yml
templates/cf-infrastructure-vsphere.yml
templates/cf-infrastructure-warden.yml

- additional_config can provide extra configuration tweaks to the postgres
config

Allow additional configuration for Postgres

---

jobs/cloud_controller_ng/spec

typo in spec

---

jobs/acceptance-tests/spec
jobs/acceptance-tests/templates/run.erb

this is blocked on https://www.pivotaltracker.com/story/show/111813688
[#111125958]
Signed-off-by: Amelia Downs <adowns@pivotal.io>

cats errand is configurable for new diego tests

---

jobs/acceptance-tests/spec
jobs/acceptance-tests/templates/config.json.erb

[#108422520]
Signed-off-by: James Myers <jmyers@pivotal.io>

make persistent app properties BOSH configurable

---

.gitmodules

Signed-off-by: John Shahid <jshahid@pivotal.io>

Remove stale submodules from .gitmodules

---

spec/fixtures/aws/cf-manifest.yml
spec/fixtures/openstack/cf-manifest.yml
spec/fixtures/vsphere/cf-manifest.yml
spec/fixtures/warden/cf-manifest.yml
templates/cf-properties.yml

[#111121616]
Signed-off-by: James Myers <jmyers@pivotal.io>

Make `disable_access_control` manifest configurable

---

spec/fixtures/aws/cf-manifest.yml
templates/cf-infrastructure-aws.yml

https://www.pivotaltracker.com/story/show/117196457

Remove unneeded router static IPs in AWS manifest template [#117196457]

---

spec/fixtures/bosh-lite/cf-manifest.yml
templates/cf-infrastructure-bosh-lite.yml

Add Diego database/role for postgres on bosh-lite

---

spec/fixtures/openstack/cf-manifest.yml
spec/fixtures/openstack/cf-stub.yml
spec/fixtures/vsphere/cf-manifest.yml
templates/cf-infrastructure-openstack.yml
templates/cf-infrastructure-vsphere.yml

[#124699851]
Signed-off-by: Nima Kaviani <nkavian@us.ibm.com>

add diego database to the list of postgres databases for openstack and vsphere

---

spec/fixtures/aws/cf-manifest.yml
spec/fixtures/bosh-lite/cf-manifest.yml
spec/fixtures/openstack/cf-manifest.yml
spec/fixtures/vsphere/cf-manifest.yml
templates/cf.yml

[#128543873]
Signed-off-by: Andrew Poydence <apoydence@pivotal.io>

Adds protocols to metron_agent properties

---

spec/fixtures/aws/cf-manifest.yml
spec/fixtures/bosh-lite/cf-manifest.yml
spec/fixtures/openstack/cf-manifest.yml
spec/fixtures/vsphere/cf-manifest.yml
templates/cf.yml

[#121083487]
Signed-off-by: Andrew Poydence <apoydence@pivotal.io>

Adds UAA property to traffic controller

---

templates/cf.yml

This just updates our consul config for doppler and trafficcontroller.
- Add zone tags to doppler and traffic controller
[#132825019]
Signed-off-by: Jason Keene <jkeene@pivotal.io>

Advertise doppler in consul

---

config/blobs.yml
packages/golang1.7-windows/packaging
packages/golang1.7-windows/spec
packages/golang1.7/packaging
packages/golang1.7/spec

[#135371379]
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>

Updates golang 1.7 to golang 1.7.4

---

spec/fixtures/aws/cf-manifest.yml
spec/fixtures/bosh-lite/cf-manifest.yml
spec/fixtures/openstack/cf-manifest.yml
spec/fixtures/vsphere/cf-manifest.yml
templates/cf-infrastructure-bosh-lite.yml
templates/cf.yml

We'd like these add these BOSH properties.
It requires that this [story](https://www.pivotaltracker.com/story/show/138835189) be accepted before it is merged. This way we don't introduced unused properties before they are consumed.

Add configuration for mutual tls between loggregator and CC

---

on-tls-certificates.md

This commit addresses:
- Fixes #1171 for properties.cc.mutual_tls.private_key
- Fixes #1172 for properties.uaa.sslCertificate and properties.uaa.sslPrivateKey

Fixes for tls documentation

---

example_manifests/minimal-aws.yml
spec/fixtures/aws/cf-manifest.yml
spec/fixtures/bosh-lite/cf-manifest.yml
spec/fixtures/openstack/cf-manifest.yml
spec/fixtures/openstack/cf-stub.yml
spec/fixtures/vsphere/cf-manifest.yml
templates/cf-infrastructure-bosh-lite.yml
templates/cf.yml

We will be removing the monolithic consul link when we bump consul-release. This PR is to support that.
Thanks,
Christian
/cc @genevievelesperance

Remove monolithic consul link.

---

templates/cf-infrastructure-bosh-lite.yml
templates/cf-infrastructure-openstack.yml
templates/cf-infrastructure-vsphere.yml

add locket database to the list of seeded dbs

---

templates/cf.yml

See https://www.pivotaltracker.com/story/show/134203563
Signed-off-by: Lisa Cho <lcho@pivotal.io>

Add healthcheck to route registrar for api jobs

---

spec/fixtures/aws/cf-manifest.yml
spec/fixtures/aws/cf-stub.yml
spec/fixtures/bosh-lite/cf-manifest.yml
spec/fixtures/openstack/cf-manifest.yml
spec/fixtures/openstack/cf-stub.yml
spec/fixtures/vsphere/cf-manifest.yml
spec/fixtures/vsphere/cf-stub.yml
templates/cf-infrastructure-bosh-lite.yml
templates/cf.yml

[#151111701](https://www.pivotaltracker.com/story/show/151111701)
Matt & @tcdowney

Add UAA client "cc_service_key_client"

---

README.md

please accept this change to the readme since RelInt is no longer supporting cf-release.

update - cf-release no longer supported
