cloudfoundry-attic/cf-release

generate_deployment_manifest
In more than one occasion we needed to pass in paths with spaces, and
`$*` bit us. This commit makes the remainder expand properly
=> The BASH gods found your lack of quotes disturbing

example_manifests/minimal-aws.yml
We're pretty certain this is required to successfully deploy the minimal aws cf.
=> Change UAA port to allow Login and UAA to colocate

templates/cf-deployment.yml
We found that VMs deployed by Bosh for CloudFoundry were not sufficiently secure: the default password for root/vcap users (c1oudc0w) could not be changed easily.
What we want:
- Possibility to change the password easily by resource_pool
- Keep the use of Spiff to generate the final template
Our patch:
- By default, the password is still c1oudc0w
- Ability to set a new password overall
```
meta:
...
default_env:
bosh:
password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
...
```
- Ability to set a password for each resource_pool
```
resource_pools:
name: small_z1
...
bosh:
password: $6$DVhgWycGMhiQYKsH$py04MGy0HVislvOLxtg/fx1RhycpbH7bSHBjxwZYC/KYg6gc59uN6LulsEk33WzggDQPBDjm0BM9iQXSzjITi1
...
```
=> Add bosh custom passwords

bosh-lite/cf-stub-spiff.yml
=> Allow load_balancer security group to be spiff-merged on bosh-lite.

config/blobs.yml, packages/buildpack_java/packaging, packages/buildpack_java/spec, packages/buildpack_java_offline/packaging, packages/buildpack_java_offline/spec
This change updates the Java Buildpack to version 2.6.1.  Version
2.6.1 ensures that the dependencies contained in the offline buildpack
are up to date.
Both the online and offline buildpacks are updated as part of this
change.
=> Java Buildpack v2.6.1

jobs/uaa/spec
Unused in templates. Below is the script we used to find unused keys; might be useful as a linter?
```ruby
#!/bin/env ruby
require 'yaml'
job_dir = '/Users/pivotal/workspace/cf-release/jobs/uaa'
spec = YAML.load_file("#{job_dir}/spec")
properties = spec['properties'].keys
erb_files = Dir["#{job_dir}/templates/*.erb"]
contents = {}
erb_files.each { |f| contents[File.basename(f)] = File.read(f) }
used = {}
properties.each do |property|
contents.each do |file, str|
if str.include?(property)
(used[property] ||= []) << file
end
end
end
puts "Used properties:"
used.each { |property, files| puts "* #{property} used by: #{files.sort.join(", ")}"}
puts
puts "Unused properties:"
(properties - used.keys).each { |property| puts "* #{property}" }
```
=> Remove unused properties from uaa job spec.

jobs/uaa/spec, jobs/uaa/templates/uaa.yml.erb, spec/fixtures/aws/cf-manifest.yml.erb, spec/fixtures/openstack/cf-manifest.yml.erb, spec/fixtures/vsphere/cf-manifest.yml.erb, spec/fixtures/warden/cf-manifest.yml.erb, templates/cf-properties.yml
In some multi-instance deployments, there can be multiple uaa url's associated with a single issuer. This allows for explicit configuration of an issuer url that is separate and distinct from the uaa url.
[#87270332]
=> Enable explicit configuration of uaa.issuer

spec/fixtures/warden/cf-manifest.yml.erb, templates/cf-infrastructure-warden.yml
Revert "Adds notification_templates.admin to UAA admin user"
This reverts commit 0e82444728bce9ebf699f68f5a16c918ba6b5b63.
This scope no longer exists in the notifications codebase.
[#90304904]
=> Remove unneeded notification_templates.admin scope from admin user

config/blobs.yml, packages/buildpack_java/packaging, packages/buildpack_java/spec, packages/buildpack_java_offline/packaging, packages/buildpack_java_offline/spec
This change updates the Java Buildpack to version 3.0. Version 3.0 has
the following highlights:
* User configuration via environment variables (via Mike Youngstrom,
Noburou Taniguchi, Guillaume Berche)
* Expanded AppDynamics configuration (via Mike Youngstrom)
* Documentation updates (via Robbie Clutton, Mohammad Asif Siddiqui)
Both the online and offline buildpacks are updated as part of this
change.
=> Java buildpack v3.0

bosh-lite/cf-stub-spiff.yml
As part of the effort to provide templates for multi-az support on mysql, we moved the deployment to new networks on bosh-lite. This requires new default running security groups.
[#87241160]
=> Add security group for cf-mysql subnets.

config/blobs.yml, packages/buildpack_go/packaging, packages/buildpack_go/spec
Upgrading to latest stable version of go buildpack
=> Upgrading go buildpack to v1.3.1

jobs/acceptance-tests/spec, jobs/acceptance-tests/templates/config.json.erb
My previous PR (https://github.com/cloudfoundry/cf-release/pull/652) got rejected
"It looks like we're already configuring the default timeouts in the CATS codebase, and we would like for that to be the source of truth for defaults. Could you please remove the defaults from the spec file to prevent any overlap? We'll be happy to pull in the PR after that."
@zrob
It seems the similar changes ended up in develop anyways
https://github.com/cloudfoundry/cf-release/commit/b6c1f33771213ded1cf7c982f5f6fafb3d900197
Anyways, here is a new PR that addresses the issue that got raised.
=> Be able to specify timeouts for acceptance tests without defaults in the spec.

bosh-lite/cf-stub-spiff.yml
Updated to new networks used in multi-AZs
=> Add security group for cf-mysql subnets

templates/cf-jobs.yml
Trying to workaround failed start by changing the template order and placing nfs_moubnter last.
See http://cf-dev.70369.x6.nabble.com/cf-dev-api-and-api-worker-jobs-fail-to-bosh-update-but-monit-start-OK-td195.html
and https://www.pivotaltracker.com/n/projects/966314/stories/94152506
=> Fixing failed cc_ng and cc_ng_worker with NFS

jobs/uaa/templates/newrelic.yml.erb, jobs/uaa/templates/uaa_ctl.erb
Extract the newrelic.environment variable into a system environment, so that 
properties:
uaa:
newrelic:
environment
takes into effect. The following sample configurations have been tested
The following triggers UAA to enable the NewRelic agent
properties.uaa.newrelic.common.license_key
or 
properties.uaa.newrelic.(properties.uaa.newrelic.environment).license_key
The default value of properties.uaa.newrelic.environment is 'production'
Sample 1: test environment that inherits common properties
properties:
uaa:
newrelic:
environment: test
common: &default_settings
license_key: 'valid-license-here'
test:
<<: *default_settings
app_name: FHANIK-New-Relic-UAA-Sample-1
error_collector:
ignore_errors: akka.actor.ActorKilledException
Sample 2 : staging environment
properties:
uaa:
newrelic: …
=> Flexible UAA NewRelic Configuration

config/blobs.yml, packages/buildpack_go/packaging, packages/buildpack_go/spec
Upgrading to latest stable version of go buildpack
=> Upgrading go buildpack to v1.4.0

packages/uaa/pre_packaging
Hi, all.
This is a simple fix that prevents putting unnecessary data to UAA package. 
This changes also cured me of the strange issue which happen when I run `bosh create release --with-tarball --force` command. When building UAA, I have following error output:
```
Building uaa...
No artifact found for uaa
Generating...
Pre-packaging...
Cannot create tarball: tar: ./java/src.zip: File removed before we read it
tar: ./java/jre/lib/zi: File removed before we read it
tar: ./java/jre/lib/ext/libatk-wrapper.so: File removed before we read it
tar: ./java/jre/lib/ext/java-atk-wrapper.jar: File removed before we read it
tar: ./java/docs: File removed before we read it
```
After I added this changes the error was solved.
=> Fix java removal in uaa pre_packaging script.

config/blobs.yml, packages/buildpack_java/packaging, packages/buildpack_java/spec, packages/buildpack_java_offline/packaging, packages/buildpack_java_offline/spec
This change updates the Java Buildpack to version 3.1. Version 3.1 has the following highlights:
* Dynatrace monitoring framework support. (via Stu Charlton)
* Introscope monitoring framework support.
* Memory calculator (via Mike Youngstrom, df007)
* Improved tar downloader (via Claude Devarenne)
* Improved OS detection (via Christopher Umbel)
Both the online and offline buildpacks are updated as part of this change.
=> Java Buildpack v3.1

generate_deployment_manifest, spec/fixtures/aws/cf-manifest.yml.erb, spec/fixtures/openstack/cf-manifest.yml.erb, spec/fixtures/vsphere/cf-manifest.yml.erb, spec/fixtures/warden/cf-manifest.yml.erb, templates/cf-deployment.yml, templates/cf-resource-pools.yml
This allows to define custom resource_pools through additional spiff template files.
For example:
```yaml
meta:
resource_pools:
server_groups:
etcd: (( merge ))
stemcell: (( merge ))                                    
resource_pools:
- <<: (( merge ))
- name: etcd_z1
cloud_properties:
<<: (( merge ))
instance_type: m1.medium
scheduler_hints:
group: (( meta.resource_pools.server_groups.etcd ))
network: cf1
stemcell: (( meta.stemcell ))
env: (( merge || meta.default_env ))                   
jobs:
- <<: (( merge ))
- name: etcd_z1
<<: (( merge ))
resource_pool: etcd_z1
```
This way we can configure the openstack server-group (which is used for vm-anti-affinity) for each job separately.
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>
=> extract resource_pools property to separate file

spec/fixtures/aws/cf-manifest.yml.erb, spec/fixtures/openstack/cf-manifest.yml.erb, spec/fixtures/vsphere/cf-manifest.yml.erb, spec/fixtures/warden/cf-manifest.yml.erb, templates/cf-properties.yml
The uaa job defines a property require_https, which could be
used to configure the uaa to accept only https requests (plaing
http requests are then redirected to https).
This patch adds the require_https property to cf-properties.yml,
so that it could be overwritten in a configuration stub file.
This is a continuation of PR 654 - https://github.com/cloudfoundry/cf-release/pull/654 , which got closed. I created a new PR as proposed there.
=> Enable uaa require https

bosh-lite/cf-stub-spiff.yml, bosh-lite/make_manifest, generate_deployment_manifest, scripts/generate_deployment_manifest
bosh-lite/make_manifest:
* remove perl dependency
* avoid making temp dir and temp stub
* avoid changing working directory
* tolerate whitespace in paths
* fix whitespace and unusual indentation
* improve variable cohesion
bosh-lite/cf-stub-spiff.yml
* add explicit spiff 'merge' directive for director_uuid
scripts/generate_deployment_manifest:
* tolerate whitespace in paths
generate_deployment_manifest:
* deprecation notice refers to deprecated file
=> Improve manifest generation scripts

jobs/acceptance-tests/spec, jobs/acceptance-tests/templates/run.erb
see also https://github.com/cloudfoundry/cf-acceptance-tests/pull/63
Mainly this bumps the submodule and adds a property to the errand to skip known-Diego-unsupported tests when running in Diego-default mode.
=> CATs are now a bit more Diego compatible

config/blobs.yml, packages/nginx/packaging, packages/nginx/spec
The latest stable version of nginx is v1.8 and includes some features we're looking to build on.
The nginx blob needs to be added and uploaded before merging:
$ wget http://nginx.org/download/nginx-1.8.0.tar.gz
$ bosh add blob ./nginx-1.8.0.tar.gz nginx
$ bosh upload blobs
=> Update to nginx 1.8

jobs/uaa/spec, jobs/uaa/templates/log4j.properties.erb, jobs/uaa/templates/varz.log4j.properties.erb
This will add timezone information and improve timestamp detection on log servers like Splunk.
=> Change UAA timestamp logging to be rfc3339 compatible

jobs/cloud_controller_ng/spec
Define properties that allow an operator to alter the access log format and the destination of the access log and the error log.
The other piece of this is a cloud controller PR since the templates were moved there and symlinked into cf-release but the specs were left behind.
=> Enable nginx log format and destination

jobs/cloud_controller_clock/spec, jobs/cloud_controller_ng/spec, jobs/cloud_controller_worker/spec
These properties should be credential for Cloud Controller's upload endpoint (not S3 or other IaaSs credential).
I took the description from the following article:
http://docs.cloudfoundry.org/deploying/cf-stub-openstack.html
> Replace the staging_upload_user: username with the account user name used to upload files to the Cloud Controller. 
> Replace the staging_upload_password: password with the password of the account used to upload files to the Cloud Controller.
=> Fix description of staging_upload_user and staging_upload_password

jobs/acceptance-tests/spec, jobs/acceptance-tests/templates/config.json.erb
In our deployments we use LDAP.  Exposing the existing user attribute allows us to run the CATs with an existing LDAP test account.
=> Add support for specifying an existing user in CATs.

jobs/cloud_controller_clock/spec, jobs/cloud_controller_ng/spec, jobs/cloud_controller_worker/spec, packages/cloud_controller_ng/packaging, packages/cloud_controller_ng/spec, packages/mysqlclient-5.5/packaging, packages/mysqlclient-5.5/spec
As part of the Ruby 2.2.3 upgrade of CC, we need to update the MySQL client used by CC. The current version of the `mysql2` gem does not work with Ruby 2.2.3. Newer versions of the `mysql2` gem need an updated `mysql-client` library. 
This PR creates a new `mysqlclient-5.5` package (next to the existing `mysqlclient`). The package itself can be found in the [tracker](https://www.pivotaltracker.com/file_attachments/51072542/download?inline=true).
The [update to Ruby 2.2.3](https://www.pivotaltracker.com/story/show/101225348) depends on this PR to be merged.
We verified that both CC unit tests and CATs are still green with MySQL and PostgreSQL:
* `mysql2` 0.3.13 (current version) + mysql-client-5.5
* `mysql2` 0.3.20 (will be the version for Ruby 2.2.3) + mysql-client-5.5
Story for the mysql …
=> Update MySQL client in cf-release

templates/cf-jobs.yml
Currently the `templates/cf-jobs.yml` template requires that the network subnets and the `static_jps` for several jobs (nats, etcd, nfs, consul, etc.) are defined.
But using alternative CPIs, like the new [Google Compute BOSH CPI](https://github.com/frodenas/bosh-google-cpi/) static IPs and subnets these values are not currently supported. 
With this PR it is possible to create a new `templates/infrastructure_gce.yml` where no static IPs are defined  (we will summit an example soon). In the stub files we can then overwrite the required values (nats, etcd, consul and NFS) to use BOSH DNS names (or other alternative service discovery).
This PR does not change the previous behaviour if the static IPs are defined and the new optional values not.  For example, for warden:
```
git checkout …
```
=> Do not require use of static_ips or subnets in spiff templates

templates/cf-jobs.yml, templates/cf-resource-pools.yml
This PR allows override the network default name and configuration (`cf1` or `cf2`) for the `router_z1` and `router_z2` jobs and their corresponding resource pools.
This feature is required in the case that a different network is needed to configure the routers' loadbalancer. For instance,  in the case of the [BOSH Google CPI](https://github.com/frodenas/bosh-google-cpi), the automatic loadbalancer registering requires the definition of alternate networks with a custom `cloud_properties.target_pool` entry.
The implementation is similar to the `ha_proxy_z1`, where a new yaml node `default_network` is defined in each job, and included if the networks are not defined in the stubs. 
This PR is related to #790, as it enables deploy Cloud Foundry using the official templates from this …
=> Allow override default network for router jobs

templates/cf-infrastructure-vsphere.yml
Fix for #794 .  This follows the same pattern as the openstack infrastructure manifest.
=> fix additional cloud_properties merging issue in cf-infrastructure-vsphere.yml

jobs/dea_next/templates/dea_ctl.erb, jobs/dea_next/templates/warden_ctl.erb
Connections are closed when no longer used which means that there will be
a minimum of 5 * 256 connections on either side in the worst case.
=> Bump the open files for DEA and Warden

jobs/dea_next/templates/dea_ctl.erb
- nf_conntrack_max is set to 65536 by default, we found linux kernel
drop tcp handshake request with the message "nf_conntrack: table
full, dropping packet" by using command "dmesg"
- in order to support higher performance, we set nf_conntrack_max
to a larger number
Signed-off-by: Yun Lv <lvyun@huawei.com>
=> Modify DEA configuration for higher performance

jobs/uaa/spec, spec/fixtures/aws/cf-manifest.yml.erb, spec/fixtures/openstack/cf-manifest.yml.erb, spec/fixtures/vsphere/cf-manifest.yml.erb, spec/fixtures/warden/cf-manifest.yml.erb, templates/cf-infrastructure-warden.yml, templates/cf-properties.yml
This removes default references to run.pivotal.io in the UAA specs and enables consumers to disable the signup and password reset links from the default login page on the UAA.
The `links.home`, `links.network`, and `links.signup-network` do not appear to be used in the UAA so they were removed entirely. If they are used, the Pivotal Network related links should likely be extracted and separated from the open source release.
=> Cleanup UAA job spec and templates

jobs/hm9000/spec, jobs/hm9000/templates/hm9000.json.erb
Large deployments can handle more than 60 concurrent messages.
=> Expose hm9000.sender_message_limit to bosh

jobs/acceptance-tests/templates/config.json.erb
Currently, the documented `cf_push_timeout`, `long_curl_timeout`, and `broker_start_timeout` options for the acceptance tests are ignored, and the default timeout is used instead. Looks like a copy-paste error.
=> fix test timeout config bug

spec/fixtures/aws/cf-manifest.yml.erb, spec/fixtures/openstack/cf-manifest.yml.erb, spec/fixtures/vsphere/cf-manifest.yml.erb, spec/fixtures/warden/cf-manifest.yml.erb, templates/cf-jobs.yml
to router properties with fixing appropriate fixtures.
This PR is replacement for https://github.com/cloudfoundry/cf-release/pull/833 and https://github.com/cloudfoundry/cf-release/pull/834 with following enhancements:
- It was forked from Development branch
- All commits are squashed together
=> Squashed commit to add 3 variables (port, status/port and debug_addr)

jobs/dea_next/spec, jobs/dea_next/templates/dea.yml.erb
Allow configuration of bandwidth limits in the DEA. This is associated with cloudfoundry/dea_ng/pull/177 and cloudfoundry/warden/pull/105.
```
dea_next:
...
instance_disk_inode_limit: 200000
instance_bandwidth_limit:
rate: 2000000
burst: 8000000
...
staging_memory_limit_mb: 1024
staging_bandwidth_limit:
rate: 2000000
burst: 8000000
...
```
=> bosh configuration for dea bandwidth limits

packages/cloud_controller_ng/spec, packages/dea_next/spec, packages/gnatsd/spec, packages/gorouter/spec, packages/warden/pre_packaging, packages/warden/spec
The idea here is to deliver a bosh.io tarball with the licenses inside each
package.tgz file distributed. The tarball ships with source code not simple
binaries and therefore should probably be shipped with licenses alongside.
- CF Slack participants told me to go ahead and open these PRs.
- This work is semi-dependent on other bits in other submodules but I was
instructed not to commit submodule pointers and instead do separate
PRs and such the submodules/repos: uaa, loggregator, etcd-release,
statsd-injector should also be merged/updated.
https://github.com/cloudfoundry-incubator/etcd-release/pull/8
https://github.com/cloudfoundry/statsd-injector/pull/1
https://github.com/cloudfoundry/uaa/pull/256
https://github.com/cloudfoundry/loggregator/pull/100
=> Add license files to final packages.

scripts/generate_deployment_manifest
Spiff command is used in the generate_deployment_manifest
script, but its installation was not checked.
Now the script checks if spiff is installed and if it's not
installed, it exits with a friendly message guiding to
the installation doc.
=> Check for spiff installation

jobs/debian_nfs_server/templates/exports.erb
- nfs_server.allow_from can now be an array of arrays
discussed with greg, dan, and dieu
reviewed by @davewalter and @sks
=> update exports template 

jobs/smoke-tests/spec, jobs/smoke-tests/templates/config.json.erb
Fixes cloudfoundry/diego-windows-release#9
[#110788502](https://www.pivotaltracker.com/story/show/110788502)
=> Add support for running Windows tests as an errand

.gitmodules
cf-routing-release was removed feece3b05a79d1250e01b16613d0e011407ff0ad
=> Remove stale submodule from .gitmodules

jobs/cloud_controller_clock/spec, jobs/cloud_controller_ng/spec, jobs/cloud_controller_worker/spec, templates/cf-properties.yml
This goes with
https://github.com/cloudfoundry/cloud_controller_ng/pull/554
The corresponding CC changes will need to be included.
=> Allow specifying a reserved set of private domains

example_manifests/minimal-aws.yml, spec/fixtures/aws/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, spec/fixtures/warden/cf-manifest.yml, templates/cf-jobs.yml
See cloudfoundry-incubator/etcd-release#9 for details. This really only applies after `etcd-release` has been bumped, but there should be no issues doing things out of order.
I'm assuming it's still desired to eventually remove the default value from `etcd-release`.  Will adjust `diego-release` after this lands.
=> ectd-release advertise url suffix

templates/cf-infrastructure-openstack.yml
This patch makes easier to enable jobs on z2 network in case of an Openstack deployment. It does not alter the default behaviour.
=> openstack: Add static IP to jobs on z2 network

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
- This is disabled by default
[#117740327]
Signed-off-by: Jason Keene <jkeene@pivotal.io>
=> Adds security_event_logging property to trafficcontroller.

jobs/gorouter/templates/gorouter_ctl.erb, src/common/utils.sh
`/proc/sys/net/core/somaxconn` isn't writeable in some container configurations, add a config value so it can be disabled.
Modify running_in_containers() so it detects Docker containers.
See https://github.com/cloudfoundry-incubator/diego-release/pull/146 for more details about the format of `/proc/self/cgroup`
=> Skip writing `somaxconn` when running in containers

example_manifests/README.md
- The term "MicroBOSH" (single-VM deployment of a BOSH director) is deprecated. Its use is both unimportant and confusing.
- Instructions for deploying BOSH director refer to *bosh-init*; the *bosh micro* plugin is deprecated should not be referenced (note that *bosh micro* plugin has nothing to do with a microBOSH director, which is another reason to get away from the term "micro".
=> Eliminate "MicroBOSH"; its use is deprecated

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
Hi!
I have changed broken login links in cf template, current values for passwd and signup return 404:
```
~$ curl -kI https://console.cf.example.corp/password_resets/new
HTTP/1.1 404 Not Found
~$ curl -kI https://console.cf.example.corp/register
HTTP/1.1 404 Not Found
```
Could you confirm this changes?
Thanks!
=> Broken login links 

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
Some infrastructures require a job to be associated with multiple networks with different configurations. While the templates used a pattern to enable that for some of the jobs (those with static IPs), it was not applied uniformly. This extends the pattern to all of the jobs in the template.
=> Use 'default_networks' pattern for all jobs

templates/cf.yml
Update the cf.yml to allow overrides for the postgres job template.
This is because postgres has been moved out of cf-release.
Thanks,
@valeriap and @christianang
=> CF template can optionally use postgres release

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
Hi:
Cloudops would like to be able specify the branding and home redirect properties in our stub file, 
Here is the PR for it, could you help review it. 
With many thanks.
=> Modify the cf template to support login branding and home redirect properties

scripts/update
The Release Engineering team has noticed that we have to run the update script multiple times in order to get a clean copy of a given version of cf-release. This seems to be a problem with cleaning up after updating the submodules of releases that are submoduled into this release.
To solve this problem, we reversed the order in which submodules are updated and cleaned, which allowed us to checkout any release and cleanse it with a single run of the script.
=> Make the update script work in a single pass.

spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/openstack/cf-stub.yml
We noticed that the `consul_agent` is missing from the `api_z1` job in the example stub at [https://docs.cloudfoundry.org/deploying/openstack/cf-stub.html](https://docs.cloudfoundry.org/deploying/openstack/cf-stub.html). Without it the api VM won't come up properly.
I also noticed that `java-buildpack` and `java-offline-buildpack` are missing and `cloud_controller_clock`  and `cloud_controller_worker` were added compared to the default values. Are those changes still supposed to be there?
=> Add consul_agent to the api_z1 job in the example manifest stub

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
This adds consul to loggregator trafficcontroller so that the TC can register itself with consul.  This shouldn't break anything on its own, but the route won't work properly until [185657bc13ab2ace36b370aa8505b39cf8e82fd8](https://github.com/cloudfoundry/loggregator/commit/185657bc13ab2ace36b370aa8505b39cf8e82fd8) is bumped for the health check script.
=> Add consul registration to trafficcontroller

.gitmodules, jobs/binary-buildpack, jobs/go-buildpack, jobs/java-buildpack, jobs/java-offline-buildpack, jobs/nodejs-buildpack, jobs/php-buildpack, jobs/python-buildpack, jobs/ruby-buildpack, jobs/staticfile-buildpack, packages/binary-buildpack, packages/buildpack_java, packages/buildpack_java_offline, packages/go-buildpack, packages/nodejs-buildpack, packages/php-buildpack, packages/python-buildpack, packages/ruby-buildpack, packages/staticfile-buildpack
The buildpacks team has updated our buildpack BOSH releases so that each releases lives in its own repo. This PR updates the submodules and symlinks so that cf-release uses the new repos. 
Tracker story: https://www.pivotaltracker.com/story/show/130042999
=> Break buildpack bosh releases into seperate repos

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
Hi:
We'd like to be able to config consul.agent.dns_config.allow_stale in our stub file, so that we can use the feature [here](https://github.com/cloudfoundry-incubator/consul-release/pull/35/commits/9617c96f24a14a3a0dcb0114ece07def063e2d4f)
Could you help review the PR?
With many thanks.
=> Add dns_config into the cf template

README.md
Spelling this out in the README is arguably nicer for users who are either searching the README or typing something like `cloud foundry ci pipeline` into a search engine.
=> Increase discoverability of CI pipeline in README

example_manifests/minimal-aws.yml, spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
30 days is likely to be a too large default for most organizations (e.g. PWS sets 1 day)
In addition, a long refresh token validity (30 days) has the current side effect of growing the UAA db potentially up to its total capacity potentially creating outages, see https://github.com/cloudfoundry/uaa/issues/466: UAA stores all refresh tokens which have not expired or were invalidated.
=> Shorter cf oauth client RT validity

templates/cf.yml
The java-offline-buildpack job is in the java-offline-buildpack BOSH release, not the java-buildpack BOSH release. This change corrects the template to account for that.
=> Correct name of release containing java-offline-buildpack job in cf.yml template

jobs/smoke-tests/spec, jobs/smoke-tests/templates/config.json.erb
This pull request has been raised regarding https://github.com/cloudfoundry/cf-release/issues/1089
It is useful to be able to ship the CF_TRACE output to temporary storage, so it can be used to debug failed tests. This pull request has been raised to allow the configuration of the artifacts directory from the manifest, which will enable the logging more easily.
Add some logic to check if the `smoke_tests.artifacts_directory` property is set and add it to the smoke test configuration. This makes it possible to turn on logging of CF_TRACE output from the manifest.
Once the template is rendered you will be left with some fairly hideous whitespace (a linefeed before and after the artifacts directory key). I did not implement trimming of this because the Bosh repository shows inconsistent …
=> Allow configuration of artifacts directory for smoke tests

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/aws/cf-stub.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/bosh-lite/cf-stub.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/openstack/cf-stub.yml, spec/fixtures/vsphere/cf-manifest.yml, spec/fixtures/vsphere/cf-stub.yml
I wanted to update the [docs](https://docs.cloudfoundry.org/deploying/aws/cf-stub.html#stub) but it turns out that the cf-stub comes from `cf-release`, hence my Pull Request here. I tried to keep this change as concise and small as possible, and I am sorry in advance if I might have missed something.
cf-release v241 release notes tell us:
[..]
This release introduces official support for running the etcd cluster
(shared by several components such as Routing API and the loggregator
subsystem, but not Diego which uses its own secure cluster) in secure
TLS mode. Upgrading an existing deployment with an insecure etcd cluster
to a secure one with minimal downtime is non-trivial. Instructions and
additional information for this procedure can be found here. If you are
using the manifest …
=> Add placeholders to make the etcd cluster run in secure TLS mode

templates/cf-infrastructure-aws.yml
- This enables using a bbl'd up environment for deploying from cf-release using its manifest generation
- Also incidentally allow extra cloud_properties to be added to router resource pools
Signed-off-by: Aakash Shah <ashah@pivotal.io>
=> Allow router resource pools to receive extra properties

spec/fixtures/bosh-lite/cf-manifest.yml, templates/cf-infrastructure-bosh-lite.yml
This got left off when we added the required keys
Signed-off-by: Jeremy Coffield <jcoffield@pivotal.io>
=> Correct SAML SP key syntax

example_manifests/minimal-aws.yml
The current deployment works by making an admin user with a password
of 'PASSWORD'
=> Further highlight that the admin user password should be replaced

src/common/utils.sh
This change allows jobs to run correctly in garden-runc containers
as well as in the previously supported garden-linux and docker containers.
=> Generalize running_in_container function

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/openstack/cf-stub.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf-infrastructure-bosh-lite.yml, templates/cf.yml
-- **DO NOT MERGE UNTIL https://www.pivotaltracker.com/story/show/136621261 IS RELEASED** --
This requires https://www.pivotaltracker.com/story/show/136621261 to be
released and merged into cf-release before it can be merged.
The clock job will hold onto a lock in the CCDB to ensure only one clock
is scheduling jobs at a time, which enables deploying more than one
instance of it.
=> Move clock_global into clock_z{1,2} to enable HA mode

example_manifests/minimal-aws.yml
Since diego etcd has been removed from the sample AWS manifest, deployment with current manifest will fail because bbs is trying to use the default `diego.bbs.etcd.machines` property. 
https://github.com/cloudfoundry/diego-release/blob/v1.5.4/jobs/bbs/spec#L83
This property should be set to an empty array to override the default bbs properties.
Here is the reference to the `bbs-overrides-no-etcd.yml` stub.
https://github.com/cloudfoundry/diego-release/blob/v1.5.4/manifest-generation/bbs-overrides-no-etcd.yml#L17
=> Add diego.bbs.etcd.machines property to minimal AWS manifest

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/openstack/cf-stub.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf-infrastructure-bosh-lite.yml, templates/cf.yml
- cloud_controller_ng
- cloud_controller_worker
- cloud_controller_job
This is to allow the job specs to optionally consume the link. Without
this change, the jobs don't know which of the multiple nats jobs to
consume the link from.
=> CAPI jobs consume nil nats links

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/openstack/cf-stub.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf-infrastructure-bosh-lite.yml, templates/cf.yml
This is to allow the job spec to optionally consume the link. Without
this change, the job don't know which of the multiple consul jobs to
consume the link from.
Signed-off-by: Derek Richard <drichard@pivotal.io>
=> Consul job consumes nil consul links

scripts/commit_with_shortlog
We are running this script in CI where the alias `ci` does not exist. Since there is no guarantee what `ci` is aliased to I would recommend being explicit with the command.
=> Remove use of alias in the commit script

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf-infrastructure-bosh-lite.yml, templates/cf.yml
- This flag tells CC whether to hand out mutual TLS droplet upload URLs to diego or the existing HTTP URLs
Signed-off-by: Sandy Cash <scarlet.tanager@gmail.com>
[#139996781]
=> Add temporary_cc_uploader_mtls property to manifests

on-tls-certificates.md
I used this guide to generate our certificates and found some typos along the way which this PR fixes.
=> Fix typos in tls certificate generation doc

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/openstack/cf-stub.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf-infrastructure-bosh-lite.yml, templates/cf.yml
- Updated HA clock implementation to avoid long-lived CPU locks which caused us to revert the previous implementation
This reverts commit 689d69b9becfc9520e2260b8a88b3e7302633f71.
[#139564797]
Signed-off-by: Eric Promislow <eric.promislow@gmail.com>
=> Take 2: Make clock_global into clock_z{1,2} to enable HA mode

spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/openstack/cf-stub.yml
We received a PR on our documentation requesting that this property be added because the user was not able to proceed without it.
=> adds ServiceProviderCertificate property to openstack stub

jobs/acceptance-tests/spec
Add `detect_timeout`, `timeout_scale`,` sleep_timeout` and `test_password` properties into acceptance tests job spec, so that these can be configured in the manifest. The properties are already passed by [config erb template](https://github.com/cloudfoundry/cf-release/blob/master/jobs/acceptance-tests/templates/config.json.erb) and [parsed by the tests](https://github.com/cloudfoundry/cf-acceptance-tests/blob/dc410aa3cc94e55b296ba7da8a6914ad3c707c44/helpers/config/config_struct.go).
I have also noticed there are further properties defined in the [cf-test-helpers](https://github.com/cloudfoundry/cf-acceptance-tests/blob/d25456f3c194fdba376fa1cc7faa919b68cbafeb/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/config/config.go#L11) that are currently not defined in the [acceptance …
=> Add acceptance tests configuration properties into spec

config/blobs.yml, jobs/smoke-tests-windows/spec, jobs/smoke-tests-windows/templates/config.json.erb, jobs/smoke-tests-windows/templates/run.ps1.erb, packages/cli-windows/packaging, packages/cli-windows/spec, packages/smoke-tests-windows/packaging, packages/smoke-tests-windows/spec
This errand can be run on a windows machine. It depends on https://github.com/cloudfoundry/cf-smoke-tests/pull/25.
@mdelillo @pnikonowicz
=> Add errand to run smoke-tests on windows

templates/cf.yml
Once a new etcd-release is cut with links, we don't want to consume it within cf-release.
Thanks,
Christian and Nick
=> Don't consume etcd link

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.conf.erb, jobs/haproxy/templates/haproxy.ctmpl.erb
This simplifies deployment manifests by allowing operators to rely on links to provide this information (e.g. from the gorouter) rather than needing to configure properties.
=> Optionally consume a router link for haproxy router servers

jobs/haproxy/spec
This reflects a change in gorouter when providing the link
=> Rename router link type to http-router

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.conf.erb
This fixes two issues with my previous PR:
1. Because router.servers defaulted to [], if the property was not
defined in the deployment manifest, it would be defaulted and the link
would not be used.
2. The original behavior did not error if no servers were specified. The
previous change would error if the property and link were both not
present. This now safely defaults to [].
=> Use router link when property is missing

packages/smoke-tests-windows/packaging, packages/smoke-tests-windows/spec
- this allows for cf-release to be precompiled on a Linux stemcell
[#143845067]
=> Adds exiter hack to smoke-tests-windows

spec/fixtures/openstack/cf-manifest.yml, templates/cf-infrastructure-openstack.yml
* all `_z2` vms should be set to zero instances, per comments in
`templates/cf-infrastructure-openstack.yml`
```
This config is for the simplest Openstack config using just one AZ.
All values for "z2" and network "cf2" are set to null. They'll end up
in the final 'spiff merge' manifest with zero instances.
```
* fixes #1180
=> Don't deploy clock_z2 on OpenStack

packages/ruby-2.1.8/packaging, packages/ruby-2.3/packaging
Always use make -j (NUM_CPU) when building ruby
Ruby build times are by far the highest in our deployments. This change allows to use bigger compilation vms to speed up deploys (especially important for stemcell bumps).
There are still a few ruby packages where the same changes should be made (e.g. nats-release)
=> Consistently use parallel make in ruby packaging

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
Move dotnet buildpack before nodejs buildpack.
New dotnet projects include package.json at the root.
Signed-off-by: Sam Coward <scoward@pivotal.io>
=> Reorder buildpacks

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/aws/cf-stub.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
Add manifest generation support for `uaa.limitedFunctionality` in the UAA job.
Story: https://www.pivotaltracker.com/story/show/151223422
- Aakash & @6palace
=> Support uaa.limitedFunctionality in UAA job

spec/fixtures/bosh-lite/cf-manifest.yml, templates/cf-infrastructure-bosh-lite.yml
- Bypassing bridge is the default behavior now.
Equivalent CF Deployment PR: https://github.com/cloudfoundry/cf-deployment/pull/337
CAPI story: https://www.pivotaltracker.com/story/show/152623585
Wait until CAPI 1.46 to merge: https://www.pivotaltracker.com/story/show/152730060
Signed-off-by: Eric Promislow <eric.promislow@suse.com>
=> Remove default bridge temporary_* flags for bosh-lite

spec/fixtures/aws/cf-manifest.yml, spec/fixtures/bosh-lite/cf-manifest.yml, spec/fixtures/openstack/cf-manifest.yml, spec/fixtures/vsphere/cf-manifest.yml, templates/cf.yml
This property is provided by capi-release, but since
bosh links and bbr are not active in cf-release, we will
disable this link for the blobstores that consume it.
[#153883420]
Signed-off-by: Elena Sharma <esharma@pivotal.io>
=> Set directories_to_backup bosh link to nil
